### ISSUE TITLE
Cannot use an integer as a constant name

### ISSUE THREAD

**Issue by elentras** [chatgris/Gaston#4]
Hi,

After a bundle update today, I just discover this error's log when starting my application :

/Users/jmortelette/.gem/gems/gaston-0.4.0/lib/gaston/builder.rb:9:in `const_defined?': wrong constant name 16 (NameError)
    from /Users/jmortelette/.gem/gems/gaston-0.4.0/lib/gaston/builder.rb:9:in`block in new'
    from /Users/jmortelette/.gem/gems/gaston-0.4.0/lib/gaston/builder.rb:6:in `each'
    from /Users/jmortelette/.gem/gems/gaston-0.4.0/lib/gaston/builder.rb:6:in`each_with_object'
    from /Users/jmortelette/.gem/gems/gaston-0.4.0/lib/gaston/builder.rb:6:in `new'
    from /Users/jmortelette/.gem/gems/gaston-0.4.0/lib/gaston/builder.rb:14:in`block in new'
    from /Users/jmortelette/.gem/gems/gaston-0.4.0/lib/gaston/builder.rb:6:in `each'
    from /Users/jmortelette/.gem/gems/gaston-0.4.0/lib/gaston/builder.rb:6:in`each_with_object'
    from /Users/jmortelette/.gem/gems/gaston-0.4.0/lib/gaston/builder.rb:6:in `new'
    from /Users/jmortelette/.gem/gems/gaston-0.4.0/lib/gaston.rb:21:in`store'
    from /Users/jmortelette/.gem/gems/gaston-0.4.0/lib/gaston.rb:42:in `configure'
    from /Users/jmortelette/Projects/MAP-social-photobook/config/initializers/_gaston.rb:2:in`<top (required)>'

**Comment by spk** [comment]
Hello,

Do you have a config sample to share for a tests case ?

Thanks

**Comment by chatgris** [comment]
Congrats, you a find a bug! :cocktail: We will look at it. :ok_hand: 

In the meantine, you should fix the version of gaston in Gemfile to the previous release:

``` ruby
gem "gaston", "~> 0.3.3"
```

Cheers

**Comment by elentras** [comment]
@chatgris Thanks ! :cool: 

@spk 
  for example :  

``` yaml
  :gaston:
    :images_dispatcher:
      :16:
        :1: 16
```

**Comment by elentras** [comment]
Nice, it's working ! Thanks !
