### ISSUE TITLE
Does Gaston encrypt/decrypt?

### ISSUE THREAD

**Issue by instantshinramen** [chatgris/Gaston#8]
Hey there, from the looks of it, Gaston doesn't seem to encrypt/decrypt the configuration. Which leads me to ask if Gaston is advisable for storing secrets (passwords, API keys, etc.). Would appreciate your thoughts!

**Comment by chatgris** [comment]
Gaston does not provide encryption out the of the box.

But, Gaston allow to have erb in configuration file, so I guess something like the following can be achieved:

``` yaml
:environment:
  :api:
    :key: <%= run_ruby_code_to_decrypt_secret(ENV['api_secret'], 'encrypt_token') %>
```
